/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package t.p.aulico;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Cristian
 */
public class MostrarEmpleado extends javax.swing.JInternalFrame {
     DefaultTableModel tab = new DefaultTableModel();
   

    /**
     * Creates new form MostrarEmpleado
     */
    public MostrarEmpleado() {
        initComponents();
        armarCabecera();
        cargarComboBox();
       
    }
    private void cargarComboBox() {
        for (Empresa empre :Empleador.lista) {
            jCempresas.addItem(empre.getRazonSocial());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCempresas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTlistado = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Lista de Empleados");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Lista de Empleados");

        jCempresas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        jCempresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCempresasActionPerformed(evt);
            }
        });

        jTlistado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTlistado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTlistadoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTlistado);

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel2.setText("Elija la empresa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(jCempresas, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(212, 212, 212)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jCempresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTlistadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTlistadoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTlistadoKeyReleased

    private void jCempresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCempresasActionPerformed
        // TODO add your handling code here:      
        borrarFilas();
                       

        for (Empresa empre : Empleador.lista) {
            if (empre.getRazonSocial().equals(jCempresas.getSelectedItem())) {
                for (Empleado e : empre.getEmpleados()) {
                    tab.addRow(new Object[]{
                        e.getCategoria(),
                        e.getDni(),
                        e.getNombre(),
                        e.getApellido()
                        });
                }
              
            }
        }
                                                

    }//GEN-LAST:event_jCempresasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCempresas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTlistado;
    // End of variables declaration//GEN-END:variables



  private void armarCabecera() {

       tab.addColumn("Categoria");
        tab.addColumn("DNI");
        tab.addColumn("Apellido");
        tab.addColumn("Nombre");

        jTlistado.setModel(tab);

    }

    private void borrarFilas() {
        int f = jTlistado.getRowCount() - 1;
        for (; f >= 0; f--) {
            tab.removeRow(f);
        }
    }
}